services:
  - type: web
    name: turfgear-backend
    runtime: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://turfgear-backend.vercel.app,https://turfgear-backend-git-main-sam-92e92f82.vercel.app
